# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código fuente
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 3: Loguearse en DockerHub (si vas a usar DockerHub)
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 4: Construir la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t demo:latest .

      # Paso 5: Etiquetar la imagen (si es necesario)
      - name: Tag Docker image
        run: |
          docker tag demo:latest danikileitor/demo:latest

      # Paso 6: Subir la imagen a DockerHub (o cualquier otro registro)
      - name: Push Docker image to DockerHub
        run: |
          docker push danikileitor/demo:latest
